services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_service
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./:/app
    command: npm run dev
  
volumes:
  psql:
    